let unicode = 0xF1900 - 1

/** @type {DeepPartial<Metadata>} */
export const metadata = {
  glyphs: {
    '.notdef': {
      zeroWidth: true,
      index: 0
    },
    ' ': {
      name: 'space',
      unicode: 32,
      zeroWidth: true
    },
    'space.cart': {
      zeroWidth: true
    },
    '(': { name: 'parenleft' },
    ')': { name: 'parenright' },
    '[': { name: 'bracketleft' },
    ']': { name: 'bracketright' },

    // U+F190x
    'tp.a': { unicode: ++unicode },
    'tp.akesi': { unicode: ++unicode },
    'tp.ala': { unicode: ++unicode },
    'tp.alasa': { unicode: ++unicode },
    'tp.ale': { unicode: ++unicode },
    'tp.anpa': { unicode: ++unicode },
    'tp.ante': { unicode: ++unicode },
    'tp.anu': { unicode: ++unicode },
    'tp.awen': { unicode: ++unicode },
    'tp.e': { unicode: ++unicode },
    'tp.en': { unicode: ++unicode },
    'tp.esun': { unicode: ++unicode },
    'tp.ijo': { unicode: ++unicode },
    'tp.ike': { unicode: ++unicode },
    'tp.ilo': { unicode: ++unicode },
    'tp.insa': { unicode: ++unicode },
    // U+F191x
    'tp.jaki': { unicode: ++unicode },
    'tp.jan': { unicode: ++unicode },
    'tp.jelo': { unicode: ++unicode },
    'tp.jo': { unicode: ++unicode },
    'tp.kala': { unicode: ++unicode },
    'tp.kalama': { unicode: ++unicode },
    'tp.kama': { unicode: ++unicode },
    'tp.kasi': { unicode: ++unicode },
    'tp.ken': { unicode: ++unicode },
    'tp.kepeken': { unicode: ++unicode },
    'tp.kili': { unicode: ++unicode },
    'tp.kiwen': { unicode: ++unicode },
    'tp.ko': { unicode: ++unicode },
    'tp.kon': { unicode: ++unicode },
    'tp.kule': { unicode: ++unicode },
    'tp.kulupu': { unicode: ++unicode },
    // U+F192x
    'tp.kute': { unicode: ++unicode },
    'tp.la': { unicode: ++unicode },
    'tp.lape': { unicode: ++unicode },
    'tp.laso': { unicode: ++unicode },
    'tp.lawa': { unicode: ++unicode },
    'tp.len': { unicode: ++unicode },
    'tp.lete': { unicode: ++unicode },
    'tp.li': { unicode: ++unicode },
    'tp.lili': { unicode: ++unicode },
    'tp.linja': { unicode: ++unicode },
    'tp.lipu': { unicode: ++unicode },
    'tp.loje': { unicode: ++unicode },
    'tp.lon': { unicode: ++unicode },
    'tp.luka': { unicode: ++unicode },
    'tp.lukin': { unicode: ++unicode },
    'tp.lupa': { unicode: ++unicode },
    // U+F193x
    'tp.ma': { unicode: ++unicode },
    'tp.mama': { unicode: ++unicode },
    'tp.mani': { unicode: ++unicode },
    'tp.meli': { unicode: ++unicode },
    'tp.mi': { unicode: ++unicode },
    'tp.mije': { unicode: ++unicode },
    'tp.moku': { unicode: ++unicode },
    'tp.moli': { unicode: ++unicode },
    'tp.monsi': { unicode: ++unicode },
    'tp.mu': { unicode: ++unicode },
    'tp.mun': { unicode: ++unicode },
    'tp.musi': { unicode: ++unicode },
    'tp.mute': { unicode: ++unicode },
    'tp.nanpa': { unicode: ++unicode },
    'tp.nasa': { unicode: ++unicode },
    'tp.nasin': { unicode: ++unicode },
    // U+F194x
    'tp.nena': { unicode: ++unicode },
    'tp.ni': { unicode: ++unicode },
    'tp.nimi': { unicode: ++unicode },
    'tp.noka': { unicode: ++unicode },
    'tp.o': { unicode: ++unicode },
    'tp.olin': { unicode: ++unicode },
    'tp.ona': { unicode: ++unicode },
    'tp.open': { unicode: ++unicode },
    'tp.pakala': { unicode: ++unicode },
    'tp.pali': { unicode: ++unicode },
    'tp.palisa': { unicode: ++unicode },
    'tp.pan': { unicode: ++unicode },
    'tp.pana': { unicode: ++unicode },
    'tp.pi': { unicode: ++unicode },
    'tp.pilin': { unicode: ++unicode },
    'tp.pimeja': { unicode: ++unicode },
    // U+F195x
    'tp.pini': { unicode: ++unicode },
    'tp.pipi': { unicode: ++unicode },
    'tp.poka': { unicode: ++unicode },
    'tp.poki': { unicode: ++unicode },
    'tp.pona': { unicode: ++unicode },
    'tp.pu': { unicode: ++unicode },
    'tp.sama': { unicode: ++unicode },
    'tp.seli': { unicode: ++unicode },
    'tp.selo': { unicode: ++unicode },
    'tp.seme': { unicode: ++unicode },
    'tp.sewi': { unicode: ++unicode },
    'tp.sijelo': { unicode: ++unicode },
    'tp.sike': { unicode: ++unicode },
    'tp.sin': { unicode: ++unicode },
    'tp.sina': { unicode: ++unicode },
    'tp.sinpin': { unicode: ++unicode },
    // U+F196x
    'tp.sitelen': { unicode: ++unicode },
    'tp.sona': { unicode: ++unicode },
    'tp.soweli': { unicode: ++unicode },
    'tp.suli': { unicode: ++unicode },
    'tp.suno': { unicode: ++unicode },
    'tp.supa': { unicode: ++unicode },
    'tp.suwi': { unicode: ++unicode },
    'tp.tan': { unicode: ++unicode },
    'tp.taso': { unicode: ++unicode },
    'tp.tawa': { unicode: ++unicode },
    'tp.telo': { unicode: ++unicode },
    'tp.tenpo': { unicode: ++unicode },
    'tp.toki': { unicode: ++unicode },
    'tp.tomo': { unicode: ++unicode },
    'tp.tu': { unicode: ++unicode },
    'tp.unpa': { unicode: ++unicode },
    // U+F197x
    'tp.uta': { unicode: ++unicode },
    'tp.utala': { unicode: ++unicode },
    'tp.walo': { unicode: ++unicode },
    'tp.wan': { unicode: ++unicode },
    'tp.waso': { unicode: ++unicode },
    'tp.wawa': { unicode: ++unicode },
    'tp.weka': { unicode: ++unicode },
    'tp.wile': { unicode: ++unicode },
    'tp.namako': { unicode: ++unicode },
    'tp.kin': { unicode: ++unicode },
    'tp.oko': { unicode: ++unicode },
    'tp.kipisi': { unicode: ++unicode },
    'tp.leko': { unicode: ++unicode },
    'tp.monsuta': { unicode: ++unicode },
    'tp.tonsi': { unicode: ++unicode },
    'tp.jasima': { unicode: ++unicode },
    // U+F198x
    'tp.kijetesantakalu': { unicode: ++unicode },
    'tp.soko': { unicode: ++unicode },
    'tp.meso': { unicode: ++unicode },
    'tp.epiku': { unicode: ++unicode },
    'tp.kokosila': { unicode: ++unicode },
    'tp.lanpan': { unicode: ++unicode },
    'tp.n': { unicode: ++unicode },
    'tp.misikeke': { unicode: ++unicode },
    'tp.ku': { unicode: ++unicode },
    // U+F199x
    'tp.startcart': {
      unicode: unicode += 8,
      ligatures: ['(', '['],
      cartouche: 'open'
    },
    'tp.endcart': {
      unicode: ++unicode,
      ligatures: [')', ']'],
      cartouche: 'close'
    },
    // U+F19Ax
    'tp.pake': { unicode: unicode += 15 },
    'tp.apeja': { unicode: ++unicode },
    'tp.majuna': { unicode: ++unicode },
    'tp.powe': { unicode: ++unicode },
    // Non-Unicode
    'tp.nimisin': { unicode: ++unicode },
    'tp.linluwi': { unicode: ++unicode },
    'tp.ali': { unicode: ++unicode }
  }
}
